blog/urls.py
from . import views
from django.urls import path
from .views import contact


urlpatterns = [
    # home page
    path('', views.PostList.as_view(), name='posts'),
    path('contact/', contact, name='contact'),

    # route for posts
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('', views.home, name="home"),
]

cms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models

from django.contrib.auth.models import User

STATUS = (
    (0, "Draft"),
    (1, "Publish"),
    (2, "Delete")
)


class Posts(models.Model):
    title = models.CharField(max_length=200, unique=True)
    content = models.TextField()
    slug = models.SlugField(max_length=200, unique=True)
    meta_description = models.CharField(max_length=300, default="new post")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField()
    updated_on = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ["-created_on"]
        verbose_name_plural = 'Posts'

    def __str__(self):  # manage models from the terminal
        return self.title


class ContactUs(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = 'Messages'

    def __str__(self):
        return '{} ({})'.format(self.name, self.email)

blog/forms.py
from django.forms import ModelForm
from . models import ContactUs


class ContactForm(ModelForm):
    class Meta:
        model = ContactUs
        fields = "__all__"

blog/views.py
from django.shortcuts import render
from django.views import generic
from . forms import ContactForm
from .models import Posts


class PostList(generic.ListView):  # views for posts
    queryset = Posts.objects.filter(status=1).order_by('-created_on')
    template_name = 'home.html'
    paginate_by = 4


class PostDetail(generic.DetailView):  # view for each post
    model = Posts
    template_name = 'post.html'


def home(request):
    return render(request, 'home.html', {})


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = ContactForm
    return render(request, 'contact.html', {'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <style>

    html, body {
            height: 100%;
    }

  body {
    font-family: sans-serif;
    font-size: 18px;
    background-color: #fdfdfd;
    display: flex;
    flex-direction: column;
  }

  #nofooter {
        flex: 1 0 auto;
  }


  #foot {
    flex-shrink: 0;
    font-family: sans-serif;
    background-color: darkgrey; color: #00308F;
    bottom: 0;
    width: 100%;
  }
    h5 {
        padding-top: 15px;
    }
    </style>

    {% block metatags %}
          <!-- will be replaced with meta content -->
    {% endblock %}
</head>
<body>
    <div id="bodydiv">
        <div id="nofooter">
            <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="topnav">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'home' %}"></a>
                    <div class="nav justify-content-end">
                        <div class="d-inline"><a class="nav-link text-black font-weight-bold" href="{% url 'posts'%}">Posts</a></div>
                    </div>
                </div>
            </nav>
            {% block content %}
                <!-- will be replaced with post content -->
            {% endblock %}
        </div>
        <footer class="footer" id="foot">
            <div class="container"><h5 style="text-align:center;"><i>Keeping you informed <small>&#62; &#62;</small></i></h5>
                <nav class="navbar navbar-expand-lg">
                    <div class="container-fluid">
                        <p><small>Copyright &copy; SerahCMS</small></p>
                        <div class="nav justify-content-center" id="navfooter">
                        <span><a class="nav-link text-black font-weight-bold" href="#">About</a></span>
                        <span><a class="nav-link text-black font-weight-bold" href="#">Overview</a></span>
                        <span><a class="nav-link text-black font-weight-bold" href="#">FAQ</a></span>
                        <span><a class="nav-link text-black font-weight-bold" href="{% url 'contact' %}">Contact</a></span>
                    </div>
                    </div>
                </nav>
            </div>
        </footer>
    </div>
</body>
</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block metatags %}
<title>SerahCMS</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
{% endblock %}

{% block content %}
    <style type="text/css">
        body {
        font-family: 'Raleway', sans-serif;
        }


        .h1, h4 {
        font-family: 'Raleway', sans-serif;
            color: white;
        }

        .card-body {
            border: none;
        }

</style>
<header class="jumbotron" style="background-color: darkgrey; color: #00308F;">
	<div class="container">
	    <p class="h1"> Spotlight your <strong>Programming &#9660;</strong></p>
    </div>
</header>
<div class="container">
	<div class="row">
		<div class="col-md-8 mt-3 left">
			{% for post in posts_list %}
			<div class="shadow-none card mb-4" id="newsfeed">
				<div class="card-body">
					<h3 class="card-title">{{ post.title }}</h3>
					<p class="card-text text-muted h6"><span>{{ post.author }}</span> | {{ post.created_on}} </p>
					<p class="card-text">{{post.meta_description }}</p>
					<span><a href="{% url 'post_detail' post.slug %}" class="btn btn-outline-primary">Read More →</a></span>
				</div>
			</div>
			{% endfor %}
		</div>
</div>
</div>
{% if is_paginated %}
    <nav aria-label="Page navigation container"></nav>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;">« PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-info" style="font-family: sans-serif;"> NEXT »</a></li>

        {% endif %}
    </ul>
{% endif %}
{%endblock%}

templates/post.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 left">
                <h1 class="card-title">{% block title %} {{ object.title }} {% endblock title %}</h1>
                <p class=" text-muted">{{ object.author }} |{{ object.created_on }}</p>

                <p class="card-text">{{ object.content | safe }}</p>

            </div>
        </div>
    </div>
{% endblock content %}